### ISSUE TITLE
Скрипты для работы с arduino

### ISSUE THREAD

**Issue by AntonovAv** [AntonovAv/trafficlight#5]
Скрипты на C работающие с GPIO библиотекой OrangePI ZERO 
интерфейсы i2c, uart 

Еще бы было интересно иметь инструкцию для установки либы на opi

**Comment by AntonovAv** [comment]
вообще, лучше не ардуино использовать, а эту плату:     
[плата](https://www.adafruit.com/product/815)    
[та, которая заказана](https://ru.aliexpress.com/item/16-Channel-12-bit-PWM-Servo-Driver-I2C-interface-PCA9685-module-for-arduino-or-Raspberry-pi/32466332558.html?spm=2114.13010608.0.0.fzVKvc)

**Comment by kirgor** [comment]
Воспользовался вот этой либой https://github.com/duxingkei33/orangepi_PC_gpio_pyH3.
Библиотека для Python, а не для C, но не думаю что это принципиально. Поставилась без проблем, только один пакет нужно поставить через apt-get, инструкцию напишу чуть позже. Проверил GPIO и I2C.

**Comment by kirgor** [comment]
Инструкция: https://github.com/AntonovAv/trafficlight/wiki/I2C,-SPI-and-GPIO-library-for-OrangePi

**Comment by AntonovAv** [comment]
Можно и на C писать с этой либой, как я понял:  [комментарий](https://forum.armbian.com/index.php?/topic/3084-orange-pi-zero-python-gpio-library/&do=findComment&comment=21534)

**Comment by kirgor** [comment]
Библиотека RPIO для node.js: https://www.npmjs.com/package/rpio

**Comment by AntonovAv** [comment]
#27
